[build]
  base = "."
  publish = "dist/andresjosehr-portfolio"
  command = "npm install --legacy-peer-deps && npm run build:prod && npm run postbuild:prod"

[build.environment]
  NODE_VERSION = "20.19.0"

[functions]
  directory = "netlify/functions"
